# Generated by Django 2.2.7 on 2019-11-30 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0015_auto_20191123_1239'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='avertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.advertise'),
        ),
        migrations.AddField(
            model_name='notification',
            name='pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
