# Generated by Django 2.2.7 on 2019-12-01 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0002_auto_20191201_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='avertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.advertise'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
