# Generated by Django 2.2.7 on 2019-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191130_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='users',
        ),
    ]
