# Generated by Django 2.2.7 on 2019-12-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_advertise_created_by'),
        ('notification', '0003_auto_20191201_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='category',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_name', related_query_name='category_name', to='advertise.category', verbose_name='category_name'),
        ),
    ]
