# Generated by Django 2.2.7 on 2019-12-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20191201_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='avertise',
            new_name='advertise',
        ),
    ]
