# Generated by Django 2.2.7 on 2019-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20191202_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redirect',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
