# Generated by Django 2.2.7 on 2019-11-23 11:18

import advertise.models.utility
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_viewer', models.IntegerField(default=1)),
                ('aprroved', models.BooleanField(default=False)),
                ('reviewed_in', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_1)),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_2)),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
