# Generated by Django 2.2.7 on 2019-12-01 10:05

import advertise.models.utility
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=600)),
                ('full_name_string', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.category')),
            ],
        ),
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aprroved', models.BooleanField(default=False)),
                ('reviewed_in', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_viewer', models.IntegerField(default=1)),
                ('details', models.TextField(default='not assigned', max_length=255)),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_1)),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_2)),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=advertise.models.utility.user_directory_path_3)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.category')),
            ],
        ),
    ]
