# Generated by Django 2.2.7 on 2019-12-01 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0002_auto_20191201_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', related_query_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
