# Generated by Django 2.2.7 on 2019-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_advertise_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='since',
            field=models.DateField(auto_created=True, default='2019-05-22'),
            preserve_default=False,
        ),
    ]
