# Generated by Django 2.2.7 on 2019-11-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
