# Generated by Django 2.2.7 on 2019-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_advertise_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='since',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
