# Generated by Django 2.2.7 on 2019-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_auto_20191217_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='contacts',
            field=models.CharField(default='01003345516', max_length=11),
        ),
    ]
