# Generated by Django 2.2.7 on 2019-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0009_auto_20191123_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name_string',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
