# Generated by Django 2.2.7 on 2019-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_advertise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='details',
            field=models.CharField(default='not assigned', max_length=255),
        ),
    ]
