# Generated by Django 2.2.7 on 2019-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0013_advertise_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='details',
            field=models.TextField(default='not assigned', max_length=255),
        ),
    ]
