# Generated by Django 2.2.7 on 2020-01-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13, unique=True)),
                ('otp', models.IntegerField(blank=True, default=999999)),
                ('otp_attempt', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('otp_is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
