# Generated by Django 2.2.7 on 2020-01-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True),
        ),
    ]
