# Generated by Django 2.2.7 on 2019-11-11 12:23

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191111_1216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.cutomUserManger()),
            ],
        ),
    ]
