# Generated by Django 2.2.7 on 2020-01-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200122_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
