# Generated by Django 2.2.7 on 2019-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='opt_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, default=999999, max_length=6),
            preserve_default=False,
        ),
    ]
