# Generated by Django 2.2.7 on 2019-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191117_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='opt_is_active',
            new_name='otp_is_active',
        ),
        migrations.AddField(
            model_name='users',
            name='otp_attempe',
            field=models.IntegerField(default=1),
        ),
    ]
