# Generated by Django 2.2.7 on 2019-11-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191117_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='otp_is_active',
            new_name='otp_is_confirmed',
        ),
    ]
