# Generated by Django 2.2.7 on 2019-11-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191117_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
