# Generated by Django 2.2.7 on 2019-11-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
